# Change these first
owner: automadcms # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Automad Documentation
    url: https://automad.org
  - name: Automad Live Demo
    url: https://try.automad.org
  - name: Automad Packages
    url: https://packages.automad.org

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/automadcms/upptime/refs/heads/master/assets/logo.svg
  favicon: https://raw.githubusercontent.com/marcantondahmen/automad/refs/heads/v1/automad/dist/favicon.ico
  name: Automad Status
  introTitle: "**System Status**"
  introMessage: This is the system status page for official Automad sites
  theme: night
  css: ":root { --body-background-color: #0e0f11; --body-text-color: #f4f4f6; --card-background-color: #151619; --nav-background-color: #0e0f11; --nav-border-bottom-color: #202327; --nav-current-border-bottom-color: #f4f4f6; --card-border-color: #202327; --up-border-left-color: #2ecc71; --tag-up-background-color: #2ecc71; }"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
